services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: scmxpertlite-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - scmxpertlite-network
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ping || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  producer:
    build:
      context: .
      dockerfile: kafka/producer/Dockerfile
    container_name: scmxpertlite-producer
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - scmxpertlite-network

  consumer:
    build:
      context: .
      dockerfile: kafka/consumer/Dockerfile
    container_name: scmxpertlite-consumer
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - scmxpertlite-network

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka-1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS="test_topic:1:1"

      - KAFKA_HEAP_OPTS=-Xms256m -Xmx256m
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - scmxpertlite-network

volumes:
  kafka_data:

networks:
  scmxpertlite-network:
    driver: bridge
